stages:
  - build
  - test
  - stage_site
  - deploy
  - cleanup

before_script:
  - apk add git make
  
build_job:
  image: python:3.6-alpine
  stage: build
  script:
  - pip install sphinx sphinx_rtd_theme sphinx-autobuild sphinx_fontawesome
  - git clone https://gitlab.com/mdr0id/test-rtd-docs.git
  - cd test-rtd-docs/
  - make html
  
test_job:
  image: python:3.6-alpine
  stage: test
  script: 
  - print "test_job not implemented"
  
stage_site_job:
  image: python:3.6-alpine
  stage: stage_site
  script:
  - sphinx-build -d _build/doctrees . _build/html
  - mv _build/html test
  artifacts:
        paths:
        - test
  only:
  - master
  
deploy_job:
  image: python:3.6-alpine
  stage: test
  script: 
  - print "deploy_job not implemented"

cleanup_job:
  image: python:3.6-alpine
  stage: test
  script: 
  - print "cleanup_job not implemented"